### ISSUE TITLE
View generated site?

### ISSUE THREAD

**Issue by awoods** [kshepherd/feed2html#1]
I successfully ran a crawl over a 150 item subset of our DSpace repository. This resulted in the OCFL objects being created in the designated output directory. However, I am not seeing any pages or an index.html. Is a full run over the entire repository required to generate site pages?

**Comment by kshepherd** [comment]
the index page generation is on my TODO sorry! did the content dir not have any HTML files?

**Comment by awoods** [comment]
You are correct... I had not dug down deep enough. I do see 'page.html' files in:
```
output/site/repository/root/oai_dash.harvard.edu_1_41384216/v1/content/
```

Thanks!
